import film1 from '../images/initialMovies/film1.png'
import film2 from '../images/initialMovies/film2.png'
import film3 from '../images/initialMovies/film3.png'
import film4 from '../images/initialMovies/film4.png'
import film5 from '../images/initialMovies/film5.png'
import film6 from '../images/initialMovies/film6.png'
import film7 from '../images/initialMovies/film7.png'
import film8 from '../images/initialMovies/film8.png'
import film9 from '../images/initialMovies/film9.png'

export const initialMovies = [
   {  country: 'Russia',
      director: 'Some Director',
      duration: 107,
      year: 2002,
      image: film1,
      trailerLink: 'https://github.com/Ksenia-Ling',
      thumbnail: film1,  
           // миниатюрное изображение постера к фильму.  
      owner: 111,
      movieId: 111,
      nameRU: "33 слова о дизайне",
      nameEN: "Name",
   },

   {  country: 'Russia',
    director: 'Some Director',
    duration: 63,
    year: 2022,
    image: film2,
    trailerLink: 'https://github.com/Ksenia-Ling',
    thumbnail: film2,
    owner: 222,
    movieId: 222,
    nameRU: "Киноальманах «100 лет дизайна»",
    nameEN: "Name",
 },

 {  country: 'Russia',
    director: 'Some Director',
    duration: 102,
    year: 2015,
    image: film3,
    trailerLink: 'https://github.com/Ksenia-Ling',
    thumbnail: film3,
    owner: 333,
    movieId: 333,
    nameRU: "В погоне за Бенкси",
    nameEN: "Name",
 },

 {  country: 'Russia',
    director: 'Some Director',
    duration: 81,
    year: 2018,
    image: film4,
    trailerLink: 'https://github.com/Ksenia-Ling',
    thumbnail: film4,
    owner: 444,
    movieId: 444,
    nameRU: "Баския: Взрыв реальности",
    nameEN: "Name",
 },

 {  country: 'Russia',
    director: 'Some Director',
    duration: 104,
    year: 2011,
    image: film5,
    trailerLink: 'https://github.com/Ksenia-Ling',
    thumbnail: film5,
    owner: 555,
    movieId: 555,
    nameRU: "Бег это свобода",
    nameEN: "Name",
 },

 {  country: 'Russia',
    director: 'Some Director',
    duration: 97,
    year: 1996,
    image: film6,
    trailerLink: 'https://github.com/Ksenia-Ling',
    thumbnail: film6,
    owner: 666,
    movieId: 666,
    nameRU: "Книготорговцы",
    nameEN: "Name",
 },

 {  country: 'Russia',
    director: 'Some Director',
    duration: 116,
    year: 1993,
    image: film7,
    trailerLink: 'https://github.com/Ksenia-Ling',
    thumbnail: film7,
    owner: 777,
    movieId: 777,
    nameRU: "Когда я думаю о Германии ночью",
    nameEN: "Name",
 },

 {  country: 'Russia',
    director: 'Some Director',
    duration: 119,
    year: 1991,
    image: film8,
    trailerLink: 'https://github.com/Ksenia-Ling',
    thumbnail: film8,
    owner: 888,
    movieId: 888,
    nameRU: "Gimme Danger: История Игги и The Stooge...",
    nameEN: "Name",
 },

 {  country: 'Russia',
    director: 'Some Director',
    duration: 102,
    year: 2008,
    image: film9,
    trailerLink: 'https://github.com/Ksenia-Ling',
    thumbnail: film9,
    owner: 999,
    movieId: 999,
    nameRU: "Дженис: Маленькая девочка грустит",
    nameEN: "Name",
 },
]